### ISSUE TITLE
代码生成报错

### ISSUE THREAD

**Issue by riusky** [Mr8god/RuoYi-Vue-PostgreSQL#1]
首先感谢开源,使用过程中遇到代码生成报错:
**
 ### 
SQL: SELECT count(0) FROM information_schema.tables WHERE table_schema = (SELECT database()) AND table_name NOT LIKE 'qrtz_%' AND table_name NOT LIKE 'gen_%' AND table_name NOT IN (SELECT table_name FROM gen_table) 
###
**
select database()  语法不通过
具体位置在GenTableMapper.xml GenTableColumnMapper.xml

**Comment by Chever-John** [comment]
Bug 已经进行了修复。问题主要在于SQL语句。感谢提出建议。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年4月30日 16:48
收件人: ***@***.***>
抄送: ***@***.***>
主题: [Mr8god/RuoYi-Vue-PostgreSQL] 代码生成报错 (#1)


首先感谢开源,使用过程中遇到代码生成报错:
**

Error querying database. Cause: org.postgresql.util.PSQLException: ERROR: relation "list_table" does not exist 位置：22 ### The error may exist in file [C:\Users\Riusky\Desktop\RuoYi-Vue-PostgreSQL\ruoyi-generator\target\classes\mapper\generator\GenTableMapper.xml] ### The error may involve com.ruoyi.generator.mapper.GenTableMapper.selectDbTableList-Inline ### The error occurred while setting parameters ### SQL: SELECT count(0) FROM list_table WHERE table_name NOT LIKE 'qrtz_%' AND table_name NOT LIKE 'gen_%' AND table_name NOT IN (SELECT table_name FROM gen_table) ### Cause: org.postgresql.util.PSQLException: ERROR: relation "list_table" does not exist 位置：22 ; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: relation "list_table" does not exist 位置：22

**
select database() 语法不通过
具体位置在GenTableMapper.xml GenTableColumnMapper.xml

―
