### ISSUE TITLE
注意 LICENSE

### ISSUE THREAD

**Issue by SkyeYoung** [Mr8god/RuoYi-Vue-PostgreSQL#2]
注意一下现在使用的开源协议，最好还是把 commit 提交到 fork 的仓库，比较尊重原作者的著作权。

**Comment by Chever-John** [comment]
Thanks and good night!


[signature_1761577781]
Chever John
Independent Developer

Github：Chever John<https://github.com/Chever-John>
***@***.***

[标题: 领英 - 说明 领英图标的图像]<https://www.linkedin.com/in/chever-john-ba852918b/>[标题: Twitter - 说明 Twitter 图标的图像]<https://twitter.com/CheverJohn>




发件人: SkyeYoung ***@***.***>
日期: 星期五, 2021年7月23日 上午11:20
收件人: Chever-John/RuoYi-Vue-PostgreSQL ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Chever-John/RuoYi-Vue-PostgreSQL] 注意 LICENSE (#2)

注意一下现在使用的开源协议，最好还是把 commit 提交到 fork 的仓库，比较尊重原作者的著作权。

―
